Fix https://github.com/brisbanesocialchess/.github/issues/102
brisbanesocialchess/.github pull request #103
Opened 2024-10-31 12:17 UTC by BaseMax

2024-10-31 12:20 UTC, jbampton commented on profile/README.md
> +    <a href="https://discord.com/invite/JWBKhQmzvD" style=text-decoration:none>
Why are the quotes removed ?

2024-10-31 12:24 UTC, BaseMax commented on profile/README.md
> +    <a href="https://discord.com/invite/JWBKhQmzvD" style=text-decoration:none>
```
profile/README.md:38:11: typography.symbols.curly_quotes Use curly quotes “”, not straight quotes "".
profile/README.md:40:142: typography.symbols.curly_quotes Use curly quotes “”, not straight quotes "".
```

2024-10-31 12:27 UTC, BaseMax commented
Now it's ready for you, John.

2024-10-31 12:29 UTC, jbampton requested changes
HTML need to be valid with quotes.

So just use a proselint ignore in a config

2024-11-01 09:07 UTC, BaseMax commented
> This branch is out-of-date with the base branch
Merge the latest changes from main into this branch.

Update

2024-12-09 20:08 UTC, closed without merging