Create .yamllint.yml
brisbanesocialchess/.github pull request #41
Opened 2024-10-28 04:51 UTC by aniruddhaadak80

Add YAML linter configuration #24

2024-10-28 08:21 UTC, jbampton requested changes
The yaml lint file should go in `.github/linters/` folder from the repo root

2024-10-28 08:26 UTC, aniruddhaadak80 commented
okey , I am changing this .Please wait .

2024-10-28 08:33 UTC, aniruddhaadak80 commented
Please review this now @jbampton .

2024-10-29 07:53 UTC, jbampton approved these changes

2024-10-29 07:53 UTC, merged